// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnTV9XOi0RfnCx-9dKQYrO2bG7dt1wfLU',
    appId: '1:570104784369:web:33100bed85d749781d1050',
    messagingSenderId: '570104784369',
    projectId: 'lab-3-flutter-project',
    authDomain: 'lab-3-flutter-project.firebaseapp.com',
    storageBucket: 'lab-3-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaZjnIr6dvutgw-VHx8DuNFwIbZPd0cvM',
    appId: '1:570104784369:android:35418805592b5eda1d1050',
    messagingSenderId: '570104784369',
    projectId: 'lab-3-flutter-project',
    storageBucket: 'lab-3-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMnH0ZYXkCaaULtmyd0lYXTJ3tS7tkmkI',
    appId: '1:570104784369:ios:64a2cd7ab82bf3181d1050',
    messagingSenderId: '570104784369',
    projectId: 'lab-3-flutter-project',
    storageBucket: 'lab-3-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMnH0ZYXkCaaULtmyd0lYXTJ3tS7tkmkI',
    appId: '1:570104784369:ios:64a2cd7ab82bf3181d1050',
    messagingSenderId: '570104784369',
    projectId: 'lab-3-flutter-project',
    storageBucket: 'lab-3-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

}